/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-11 06:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Entity.User;
import com.Entity.Book_Details;
import java.util.List;
import com.DAO.BookADO_impl;
import java.sql.Connection;
import com.DB.DB_Connect;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/allcomponent/navbar.jsp", Long.valueOf(1660119267659L));
    _jspx_dependants.put("/allcomponent/allCss.jsp", Long.valueOf(1659767488752L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659355740106L));
    _jspx_dependants.put("/allcomponent/footer.jsp", Long.valueOf(1659772071710L));
    _jspx_dependants.put("jar:file:/C:/Users/susha/Documents/workspace-spring-tool-suite-4-4.15.1.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/EBook_App/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153364382000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.DB.DB_Connect");
    _jspx_imports_classes.add("com.Entity.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.Entity.Book_Details");
    _jspx_imports_classes.add("com.DAO.BookADO_impl");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>EBook</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"allcomponent/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".bg_img {\r\n");
      out.write("	background-image: url(\"image/ebook.jpg\");\r\n");
      out.write("	height: 50vh;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".recentBook {\r\n");
      out.write("	margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".recentBook:hover {\r\n");
      out.write("	background-color: #f7f7f7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body p {\r\n");
      out.write("	height: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".justify-content-center a {\r\n");
      out.write("	margin-bottom: 4px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #fcf7f7\">\r\n");
      out.write("\r\n");
      out.write("	");

	User u = (User) session.getAttribute("userObj");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" style=\"height: 12px; background: #303f9f\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container-fluid p-3 bg-light\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-md-3 col-sm-3 mt-2 text-success\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				<a href=\"index.jsp\" style=\"text-decoration: none;\" class=\"text-success\"><i class=\"fas fa-home\"></i> EBooks</a>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("			<form class=\"form-inline my-2 my-lg-0\" action=\"Search_Book.jsp\" method=\"post\">\r\n");
      out.write("				<input class=\"form-control mr-sm-2\" type=\"search Books\" name=\"srch_char\"\r\n");
      out.write("					placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("				<button class=\"btn btn-primary my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg_custom\">\r\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("		<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.jsp\"><i\r\n");
      out.write("					class=\"fas fa-home\"></i> Home <span class=\"sr-only\">(current)</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("				href=\"All_recentBooks.jsp\"><i class=\"fas fa-book-open\"></i>\r\n");
      out.write("					Recent Book</a></li>\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("				href=\"All_newBooks.jsp\"><i class=\"fas fa-book-open\"></i> New\r\n");
      out.write("					Book</a></li>\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("				href=\"All_oldBooks.jsp\"><i class=\"fas fa-book-open\"></i> Old\r\n");
      out.write("					Book</a></li>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<a href=\"Setting.jsp\" class=\"btn btn-light my-2 my-sm-0\">\r\n");
      out.write("			<i class=\"fas fa-cog\"></i> Setting\r\n");
      out.write("		</a>\r\n");
      out.write("		<a href=\"\" class=\"btn btn-light my-2 my-sm-0 ml-1\">\r\n");
      out.write("			<i class=\"fas fa-phone\"></i> Contact Us\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid bg_img\">\r\n");
      out.write("		<h2 class=\"text-center text-danger p-4\">\r\n");
      out.write("			<i class=\"fas fa-home\"></i> Ebook Management System\r\n");
      out.write("		</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Recent Book Start -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center p-2\">Recent Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");

			BookADO_impl dao2 = new BookADO_impl(DB_Connect.getConnect());
			List<Book_Details> list2 = dao2.getRecentBooks();
			for (Book_Details bd : list2) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-lg-3 col-md-4 col-sm-6 col-12\">\r\n");
      out.write("				<div class=\"card recentBook\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img src=\"book_Photos/");
      out.print(bd.getBookimg());
      out.write("\" class=\"img-thumbnail\"\r\n");
      out.write("							style=\"width: 150px; height: 200px; margin-bottom: 12px;\">\r\n");
      out.write("						<p>");
      out.print(bd.getBookname());
      out.write("</p>\r\n");
      out.write("						<p>");
      out.print(bd.getBookauthor());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("						");

						if (bd.getBookcategory().equals("old")) {
						
      out.write("\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories :\r\n");
      out.write("							");
      out.print(bd.getBookcategory());
      out.write("\r\n");
      out.write("						</p>\r\n");
      out.write("						<div class=\"row mt-4 justify-content-center\">\r\n");
      out.write("							<a href=\"View_books.jsp?bid=");
      out.print(bd.getBookid());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\">");
      out.print(bd.getBookprice());
      out.write("</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories :\r\n");
      out.write("							");
      out.print(bd.getBookcategory());
      out.write("\r\n");
      out.write("						</p>\r\n");
      out.write("						<div class=\"row mt-4 justify-content-center\">\r\n");
      out.write("							");

							if (u == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"Login.jsp\" class=\"btn btn-danger btn-sm ml-2\"><i\r\n");
      out.write("								class=\"fas fa-cart-plus\"></i> Add Cart</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"cart?bid=");
      out.print(bd.getBookid());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-2\"><i\r\n");
      out.write("								class=\"fas fa-cart-plus\"></i> Add Cart</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("							<a href=\"View_books.jsp?bid=");
      out.print(bd.getBookid());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\">");
      out.print(bd.getBookprice());
      out.write("</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-2\">\r\n");
      out.write("			<a href=\"All_recentBooks.jsp\"\r\n");
      out.write("				class=\"btn btn-danger btn-sm text-white\">View All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Recent Book End -->\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- New Book Start -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">New Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("			");

			BookADO_impl dao = new BookADO_impl(DB_Connect.getConnect());
			List<Book_Details> list = dao.getNewBooks();
			for (Book_Details b : list) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-lg-3 col-md-4 col-sm-6 col-12\">\r\n");
      out.write("				<div class=\"card recentBook\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img src=\"book_Photos/");
      out.print(b.getBookimg());
      out.write("\" class=\"img-thumbnail\"\r\n");
      out.write("							style=\"width: 180px; height: 200px; object-fit: cover; margin-bottom: 12px;\">\r\n");
      out.write("						<p>");
      out.print(b.getBookname());
      out.write("</p>\r\n");
      out.write("						<p>");
      out.print(b.getBookauthor());
      out.write("</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories :\r\n");
      out.write("							");
      out.print(b.getBookcategory());
      out.write("</p>\r\n");
      out.write("						<div class=\"row mt-4 justify-content-center\">\r\n");
      out.write("							");

							if (u == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"Login.jsp\" class=\"btn btn-danger btn-sm ml-2\"><i\r\n");
      out.write("								class=\"fas fa-cart-plus\"></i> Add Cart</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"cart?bid=");
      out.print(b.getBookid());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-2\"><i\r\n");
      out.write("								class=\"fas fa-cart-plus\"></i> Add Cart</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("							<a href=\"View_books.jsp?bid=");
      out.print(b.getBookid());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\">");
      out.print(b.getBookprice());
      out.write("</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-2\">\r\n");
      out.write("			<a href=\"All_newBooks.jsp\" class=\"btn btn-danger btn-sm text-white\">View\r\n");
      out.write("				All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- New Book End -->\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- Old Book Start -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"text-center\">Old Book</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");

			BookADO_impl oldbk = new BookADO_impl(DB_Connect.getConnect());
			List<Book_Details> listb = oldbk.getOldBooks();
			for (Book_Details bds : listb) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-lg-3 col-md-4 col-sm-6 col-12\">\r\n");
      out.write("				<div class=\"card recentBook\">\r\n");
      out.write("					<div class=\"card-body text-center\">\r\n");
      out.write("						<img src=\"book_Photos/");
      out.print(bds.getBookimg());
      out.write("\" class=\"img-thumbnail\"\r\n");
      out.write("							style=\"width: 180px; height: 200px; object-fit: cover; margin-bottom: 12px;\">\r\n");
      out.write("						<p>");
      out.print(bds.getBookname());
      out.write("</p>\r\n");
      out.write("						<p>");
      out.print(bds.getBookauthor());
      out.write("</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Categories :\r\n");
      out.write("							");
      out.print(bds.getBookcategory());
      out.write("</p>\r\n");
      out.write("						<div class=\"row mt-4 justify-content-center\">\r\n");
      out.write("							<a href=\"View_books.jsp?bid=");
      out.print(bds.getBookid());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-success btn-sm ml-1\">View Details</a> <a href=\"\"\r\n");
      out.write("								class=\"btn btn-danger btn-sm ml-1\">");
      out.print(bds.getBookprice());
      out.write("</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center mt-2\">\r\n");
      out.write("			<a href=\"All_oldBooks.jsp\" class=\"btn btn-danger btn-sm text-white\">View\r\n");
      out.write("				All</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Old Book End -->\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<div class=\"container-fluid text-center text-white p-3\" style=\"background-color: #303f9f;\">\r\n");
      out.write("	<h5 class=\"mt-2\">Designed and Devloped by Sushant Chaudhary</h5>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /allcomponent/navbar.jsp(21,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userObj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<div class=\"col-md-3 col-sm-3 \">\r\n");
          out.write("				<a href=\"CheckOut.jsp\"><i class=\"fas fa-cart-plus fa-2x\"></i></a>\r\n");
          out.write("				<a href=\"Home.jsp\" class=\"btn btn-success mb-1\"><i\r\n");
          out.write("					class=\"fas fa-user-plus\"></i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a> <a\r\n");
          out.write("					href=\"Logout\" class=\"btn btn-primary text-white\"> <i\r\n");
          out.write("					class=\"fas fa-sign-in-alt\"></i> Logout\r\n");
          out.write("				</a>\r\n");
          out.write("			</div>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /allcomponent/navbar.jsp(31,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<div class=\"col-md-3 col-sm-3 \">\r\n");
          out.write("				<a href=\"Login.jsp\" class=\"btn btn-success mb-1\"><i\r\n");
          out.write("					class=\"fas fa-sign-in-alt\"></i> Login</a> <a href=\"Register.jsp\"\r\n");
          out.write("					class=\"btn btn-primary text-white\"><i class=\"fas fa-user-plus\"></i>\r\n");
          out.write("					Register</a>\r\n");
          out.write("			</div>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
